[versions]
agp = "8.12.3"
airship = "19.13.3"

# AndroidX
androidx-navigation = '2.7.7'
androidx-preference = '1.2.1'

# Glance
androidx-glance = '1.1.1'

# Kotlin
kotlin = "2.0.21"
kotlinx-coroutines = '1.8.1'
kotlinx-serialization = '1.6.3'

# Material
google-material = '1.12.0'

[libraries]
# Airship
airship-fcm = { module = "com.urbanairship.android:urbanairship-fcm", version.ref = "airship" }
airship-preferencecenter = { module = "com.urbanairship.android:urbanairship-preference-center", version.ref = "airship" }
airship-messagecenter = { module = "com.urbanairship.android:urbanairship-message-center", version.ref = "airship" }
airship-liveupdate = { module = "com.urbanairship.android:urbanairship-live-update", version.ref = "airship" }
airship-automation = { module = "com.urbanairship.android:urbanairship-automation", version.ref = "airship" }
airship-debug = { module = "com.urbanairship.android:urbanairship-debug", version.ref = "airship" }

# AndroidX
androidx-navigation-fragmentktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "androidx-navigation" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }

# Glance
glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "androidx-glance" }

# Kotlin
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines"}
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines"}
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# Material
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinx-serialization = { id = 'org.jetbrains.kotlin.plugin.serialization', version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
