[versions]
agp = "8.13.0"
airship = "20.0.1"

# AndroidX
androidx-activity-compose = '1.11.0'
androidx-lifecycle = '2.9.4'
androidx-appcompat = '1.7.1'
androidx-core = '1.17.0'

# Compose
compose-bom = '2025.10.01'

# Glance
androidx-glance = '1.1.1'

# Kotlin
kotlin = "2.2.21"
kotlinx-serialization = '1.9.0'

# Navigation3
nav3Core = "1.0.0-alpha11"
lifecycleViewmodelNav3 = "1.0.0-alpha04"

[libraries]
# Airship
airship-fcm = { module = "com.urbanairship.android:urbanairship-fcm", version.ref = "airship" }
airship-preferencecenter-compose = { module = "com.urbanairship.android:urbanairship-preference-center-compose", version.ref = "airship" }
airship-messagecenter-compose = { module = "com.urbanairship.android:urbanairship-message-center-compose", version.ref = "airship" }
airship-liveupdate = { module = "com.urbanairship.android:urbanairship-live-update", version.ref = "airship" }
airship-automation-compose = { module = "com.urbanairship.android:urbanairship-automation-compose", version.ref = "airship" }
airship-debug = { module = "com.urbanairship.android:urbanairship-debug", version.ref = "airship" }

# AndroidX
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref="androidx-lifecycle" }
androidx-core = { module = "androidx.core:core", version.ref = "androidx-core" }

# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui-viewbinding = { group = "androidx.compose.ui", name = "ui-viewbinding" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

# Glance
glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "androidx-glance" }

# Kotlin
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinx-serialization = { id = 'org.jetbrains.kotlin.plugin.serialization', version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
