plugins {
    id 'kotlin-android'
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlinx.serialization)
    alias(libs.plugins.compose.compiler)
}

android {
    namespace 'com.airship.sample'
    compileSdk = 36

    defaultConfig {
        applicationId "com.airship.sample"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0"
        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        viewBinding = true
        buildConfig true
        compose = true
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17
    }
}

dependencies {
    // Kotlin
    implementation(libs.kotlinx.serialization.json)

    //Airship
    implementation(libs.airship.fcm)
    implementation(libs.airship.automation.compose)
    implementation(libs.airship.messagecenter.compose)
    implementation(libs.airship.preferencecenter.compose)
    implementation(libs.airship.liveupdate)
    // Included as an implementation dependency so that we can embed the debug screen as a tab
    // in our sample app. Apps that do not wish to embed the debug screen can omit this dependency
    // or use debugImplementation instead.
    implementation(libs.airship.debug)

    // AndroidX
    implementation(libs.androidx.core)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.coordinatorlayout)
    implementation(libs.androidx.fragment.ktx)
    implementation(libs.androidx.navigation3.runtime)
    implementation(libs.androidx.navigation3.ui)
    implementation(libs.androidx.lifecycle.viewmodel.navigation3)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)

    // Compose
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.material3)
    implementation(libs.compose.material.icons.core)
    implementation(libs.compose.ui.viewbinding)
    implementation(libs.compose.ui.tooling)

    // Glance
    implementation(libs.glance.appwidget)

    // Glide
    implementation(libs.glide)

    // Google
    implementation(libs.google.material)
}

def googleServicesFile = rootProject.file('app/google-services.json')
if (googleServicesFile.exists()) {
    apply plugin: 'com.google.gms.google-services'  // Google Play services Gradle plugin
}